CREATE TABLE [dbo].[TB_CONTATO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[NOME] [nvarchar](100) NOT NULL,
	[EMAIL] [nvarchar](100) NULL,
	[TELEFONE] [nvarchar](11) NULL
	)

GO

CREATE PROCEDURE STP_INS_CONTATO

	@NOME nvarchar(100),
	@EMAIL nvarchar(100),
	@TELEFONE nvarchar(11)
	AS
BEGIN
	
   INSERT INTO TB_CONTATO (NOME,EMAIL,TELEFONE)VALUES(@NOME,@EMAIL,@TELEFONE)
END

GO

CREATE PROCEDURE STP_UPD_CONTATO

    @ID bigint,
	@NOME nvarchar(100),
	@EMAIL nvarchar(100),
	@TELEFONE nvarchar(11)
	AS
BEGIN
   UPDATE TB_CONTATO SET NOME = @NOME, EMAIL = @EMAIL, TELEFONE = @TELEFONE
   WHERE ID = @ID
END

GO

CREATE PROCEDURE STP_DEL_CONTATO

    @ID bigint
	AS
BEGIN

   DELETE TB_CONTATO  
   WHERE ID = @ID
END

GO

CREATE PROCEDURE STP_SEL_CONTATO_ByID
 @ID bigint
	AS

BEGIN

   SELECT * FROM TB_CONTATO
   WHERE ID = @ID
END


ALTER PROCEDURE STP_SEL_CONTATO
    @NOME nvarchar(100) = NULL,
	@EMAIL nvarchar(100) =  NULL,
	@TELEFONE nvarchar(11) = NULL

	AS

BEGIN

   SELECT * FROM TB_CONTATO
   WHERE 
      (@NOME IS NULL OR NOME LIKE '%' + @NOME + '%') AND
	  (@EMAIL IS NULL OR EMAIL LIKE '%' + @EMAIL + '%') AND
	  (@TELEFONE IS NULL OR TELEFONE LIKE '%' + @TELEFONE +'%') 
	  
END




EXEC STP_INS_CONTATO

@NOME='TESTE '
,@EMAIL='TESTE45555'
,@TELEFONE='1458'




